// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsmith/nknsdk/network/proto/messagepayloadP.proto

package jsmith.nknsdk.network.proto;

public final class MessagepayloadP {
  private MessagepayloadP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code jsmith.nknsdk.network.proto.MessagePayloadType}
   */
  public enum MessagePayloadType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BINARY = 0;</code>
     */
    BINARY(0),
    /**
     * <code>TEXT = 1;</code>
     */
    TEXT(1),
    /**
     * <code>ACK = 2;</code>
     */
    ACK(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BINARY = 0;</code>
     */
    public static final int BINARY_VALUE = 0;
    /**
     * <code>TEXT = 1;</code>
     */
    public static final int TEXT_VALUE = 1;
    /**
     * <code>ACK = 2;</code>
     */
    public static final int ACK_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessagePayloadType valueOf(int value) {
      return forNumber(value);
    }

    public static MessagePayloadType forNumber(int value) {
      switch (value) {
        case 0: return BINARY;
        case 1: return TEXT;
        case 2: return ACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessagePayloadType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessagePayloadType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessagePayloadType>() {
            public MessagePayloadType findValueByNumber(int number) {
              return MessagePayloadType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MessagepayloadP.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessagePayloadType[] VALUES = values();

    public static MessagePayloadType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessagePayloadType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jsmith.nknsdk.network.proto.MessagePayloadType)
  }

  public interface MessagePayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.MessagePayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
     */
    MessagepayloadP.MessagePayloadType getType();

    /**
     * <code>bytes pid = 2;</code>
     */
    com.google.protobuf.ByteString getPid();

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bytes reply_to_pid = 4;</code>
     */
    com.google.protobuf.ByteString getReplyToPid();

    /**
     * <code>bool no_ack = 5;</code>
     */
    boolean getNoAck();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.MessagePayload}
   */
  public  static final class MessagePayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.MessagePayload)
      MessagePayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessagePayload.newBuilder() to construct.
    private MessagePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessagePayload() {
      type_ = 0;
      pid_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      replyToPid_ = com.google.protobuf.ByteString.EMPTY;
      noAck_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessagePayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              pid_ = input.readBytes();
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 34: {

              replyToPid_ = input.readBytes();
              break;
            }
            case 40: {

              noAck_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_MessagePayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_MessagePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagepayloadP.MessagePayload.class, MessagepayloadP.MessagePayload.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
     */
    public MessagepayloadP.MessagePayloadType getType() {
      @SuppressWarnings("deprecation")
      MessagepayloadP.MessagePayloadType result = MessagepayloadP.MessagePayloadType.valueOf(type_);
      return result == null ? MessagepayloadP.MessagePayloadType.UNRECOGNIZED : result;
    }

    public static final int PID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pid_;
    /**
     * <code>bytes pid = 2;</code>
     */
    public com.google.protobuf.ByteString getPid() {
      return pid_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int REPLY_TO_PID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString replyToPid_;
    /**
     * <code>bytes reply_to_pid = 4;</code>
     */
    public com.google.protobuf.ByteString getReplyToPid() {
      return replyToPid_;
    }

    public static final int NO_ACK_FIELD_NUMBER = 5;
    private boolean noAck_;
    /**
     * <code>bool no_ack = 5;</code>
     */
    public boolean getNoAck() {
      return noAck_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != MessagepayloadP.MessagePayloadType.BINARY.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!pid_.isEmpty()) {
        output.writeBytes(2, pid_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (!replyToPid_.isEmpty()) {
        output.writeBytes(4, replyToPid_);
      }
      if (noAck_ != false) {
        output.writeBool(5, noAck_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != MessagepayloadP.MessagePayloadType.BINARY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!pid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pid_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (!replyToPid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, replyToPid_);
      }
      if (noAck_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, noAck_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagepayloadP.MessagePayload)) {
        return super.equals(obj);
      }
      MessagepayloadP.MessagePayload other = (MessagepayloadP.MessagePayload) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getPid()
          .equals(other.getPid());
      result = result && getData()
          .equals(other.getData());
      result = result && getReplyToPid()
          .equals(other.getReplyToPid());
      result = result && (getNoAck()
          == other.getNoAck());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + REPLY_TO_PID_FIELD_NUMBER;
      hash = (53 * hash) + getReplyToPid().hashCode();
      hash = (37 * hash) + NO_ACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNoAck());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagepayloadP.MessagePayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagepayloadP.MessagePayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagepayloadP.MessagePayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagepayloadP.MessagePayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagepayloadP.MessagePayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagepayloadP.MessagePayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagepayloadP.MessagePayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.MessagePayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.MessagePayload)
        MessagepayloadP.MessagePayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_MessagePayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_MessagePayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagepayloadP.MessagePayload.class, MessagepayloadP.MessagePayload.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.Messagepayload.MessagePayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        pid_ = com.google.protobuf.ByteString.EMPTY;

        data_ = com.google.protobuf.ByteString.EMPTY;

        replyToPid_ = com.google.protobuf.ByteString.EMPTY;

        noAck_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_MessagePayload_descriptor;
      }

      @java.lang.Override
      public MessagepayloadP.MessagePayload getDefaultInstanceForType() {
        return MessagepayloadP.MessagePayload.getDefaultInstance();
      }

      @java.lang.Override
      public MessagepayloadP.MessagePayload build() {
        MessagepayloadP.MessagePayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessagepayloadP.MessagePayload buildPartial() {
        MessagepayloadP.MessagePayload result = new MessagepayloadP.MessagePayload(this);
        result.type_ = type_;
        result.pid_ = pid_;
        result.data_ = data_;
        result.replyToPid_ = replyToPid_;
        result.noAck_ = noAck_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagepayloadP.MessagePayload) {
          return mergeFrom((MessagepayloadP.MessagePayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagepayloadP.MessagePayload other) {
        if (other == MessagepayloadP.MessagePayload.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getPid() != com.google.protobuf.ByteString.EMPTY) {
          setPid(other.getPid());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getReplyToPid() != com.google.protobuf.ByteString.EMPTY) {
          setReplyToPid(other.getReplyToPid());
        }
        if (other.getNoAck() != false) {
          setNoAck(other.getNoAck());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagepayloadP.MessagePayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagepayloadP.MessagePayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
       */
      public MessagepayloadP.MessagePayloadType getType() {
        @SuppressWarnings("deprecation")
        MessagepayloadP.MessagePayloadType result = MessagepayloadP.MessagePayloadType.valueOf(type_);
        return result == null ? MessagepayloadP.MessagePayloadType.UNRECOGNIZED : result;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
       */
      public Builder setType(MessagepayloadP.MessagePayloadType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.MessagePayloadType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes pid = 2;</code>
       */
      public com.google.protobuf.ByteString getPid() {
        return pid_;
      }
      /**
       * <code>bytes pid = 2;</code>
       */
      public Builder setPid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes pid = 2;</code>
       */
      public Builder clearPid() {
        
        pid_ = getDefaultInstance().getPid();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString replyToPid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes reply_to_pid = 4;</code>
       */
      public com.google.protobuf.ByteString getReplyToPid() {
        return replyToPid_;
      }
      /**
       * <code>bytes reply_to_pid = 4;</code>
       */
      public Builder setReplyToPid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replyToPid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes reply_to_pid = 4;</code>
       */
      public Builder clearReplyToPid() {
        
        replyToPid_ = getDefaultInstance().getReplyToPid();
        onChanged();
        return this;
      }

      private boolean noAck_ ;
      /**
       * <code>bool no_ack = 5;</code>
       */
      public boolean getNoAck() {
        return noAck_;
      }
      /**
       * <code>bool no_ack = 5;</code>
       */
      public Builder setNoAck(boolean value) {
        
        noAck_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool no_ack = 5;</code>
       */
      public Builder clearNoAck() {
        
        noAck_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.MessagePayload)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.MessagePayload)
    private static final MessagepayloadP.MessagePayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagepayloadP.MessagePayload();
    }

    public static MessagepayloadP.MessagePayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessagePayload>
        PARSER = new com.google.protobuf.AbstractParser<MessagePayload>() {
      @java.lang.Override
      public MessagePayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagePayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessagePayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessagePayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessagepayloadP.MessagePayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TextDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.TextData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.TextData}
   */
  public  static final class TextData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.TextData)
      TextDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextData.newBuilder() to construct.
    private TextData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextData() {
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_TextData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_TextData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagepayloadP.TextData.class, MessagepayloadP.TextData.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagepayloadP.TextData)) {
        return super.equals(obj);
      }
      MessagepayloadP.TextData other = (MessagepayloadP.TextData) obj;

      boolean result = true;
      result = result && getText()
          .equals(other.getText());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagepayloadP.TextData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagepayloadP.TextData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagepayloadP.TextData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagepayloadP.TextData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagepayloadP.TextData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagepayloadP.TextData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagepayloadP.TextData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagepayloadP.TextData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagepayloadP.TextData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagepayloadP.TextData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagepayloadP.TextData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagepayloadP.TextData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagepayloadP.TextData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.TextData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.TextData)
        MessagepayloadP.TextDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_TextData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_TextData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagepayloadP.TextData.class, MessagepayloadP.TextData.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.Messagepayload.TextData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagepayloadP.internal_static_jsmith_nknsdk_network_proto_TextData_descriptor;
      }

      @java.lang.Override
      public MessagepayloadP.TextData getDefaultInstanceForType() {
        return MessagepayloadP.TextData.getDefaultInstance();
      }

      @java.lang.Override
      public MessagepayloadP.TextData build() {
        MessagepayloadP.TextData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessagepayloadP.TextData buildPartial() {
        MessagepayloadP.TextData result = new MessagepayloadP.TextData(this);
        result.text_ = text_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagepayloadP.TextData) {
          return mergeFrom((MessagepayloadP.TextData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagepayloadP.TextData other) {
        if (other == MessagepayloadP.TextData.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagepayloadP.TextData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagepayloadP.TextData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.TextData)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.TextData)
    private static final MessagepayloadP.TextData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagepayloadP.TextData();
    }

    public static MessagepayloadP.TextData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextData>
        PARSER = new com.google.protobuf.AbstractParser<TextData>() {
      @java.lang.Override
      public TextData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessagepayloadP.TextData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_MessagePayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_MessagePayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_TextData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_TextData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0jsmith/nknsdk/network/proto/messagepay" +
      "load.proto\022\033jsmith.nknsdk.network.proto\"" +
      "\220\001\n\016MessagePayload\022=\n\004type\030\001 \001(\0162/.jsmit" +
      "h.nknsdk.network.proto.MessagePayloadTyp" +
      "e\022\013\n\003pid\030\002 \001(\014\022\014\n\004data\030\003 \001(\014\022\024\n\014reply_to" +
      "_pid\030\004 \001(\014\022\016\n\006no_ack\030\005 \001(\010\"\030\n\010TextData\022\014" +
      "\n\004text\030\001 \001(\t*3\n\022MessagePayloadType\022\n\n\006BI" +
      "NARY\020\000\022\010\n\004TEXT\020\001\022\007\n\003ACK\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jsmith_nknsdk_network_proto_MessagePayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jsmith_nknsdk_network_proto_MessagePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_MessagePayload_descriptor,
        new java.lang.String[] { "Type", "Pid", "Data", "ReplyToPid", "NoAck", });
    internal_static_jsmith_nknsdk_network_proto_TextData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jsmith_nknsdk_network_proto_TextData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_TextData_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
