// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsmith/nknsdk/network/proto/messagesP.proto

package jsmith.nknsdk.network.proto;

public final class MessagesP {
  private MessagesP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientToNodeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.ClientToNodeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dest = 1;</code>
     */
    java.lang.String getDest();
    /**
     * <code>string dest = 1;</code>
     */
    com.google.protobuf.ByteString
        getDestBytes();

    /**
     * <code>bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>repeated string dests = 3;</code>
     */
    java.util.List<java.lang.String>
        getDestsList();
    /**
     * <code>repeated string dests = 3;</code>
     */
    int getDestsCount();
    /**
     * <code>repeated string dests = 3;</code>
     */
    java.lang.String getDests(int index);
    /**
     * <code>repeated string dests = 3;</code>
     */
    com.google.protobuf.ByteString
        getDestsBytes(int index);

    /**
     * <code>uint32 max_holding_seconds = 4;</code>
     */
    int getMaxHoldingSeconds();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.ClientToNodeMessage}
   */
  public  static final class ClientToNodeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.ClientToNodeMessage)
      ClientToNodeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientToNodeMessage.newBuilder() to construct.
    private ClientToNodeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientToNodeMessage() {
      dest_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      maxHoldingSeconds_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientToNodeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dest_ = s;
              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                dests_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              dests_.add(s);
              break;
            }
            case 32: {

              maxHoldingSeconds_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          dests_ = dests_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagesP.internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagesP.internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagesP.ClientToNodeMessage.class, MessagesP.ClientToNodeMessage.Builder.class);
    }

    private int bitField0_;
    public static final int DEST_FIELD_NUMBER = 1;
    private volatile java.lang.Object dest_;
    /**
     * <code>string dest = 1;</code>
     */
    public java.lang.String getDest() {
      java.lang.Object ref = dest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dest_ = s;
        return s;
      }
    }
    /**
     * <code>string dest = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDestBytes() {
      java.lang.Object ref = dest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int DESTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList dests_;
    /**
     * <code>repeated string dests = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDestsList() {
      return dests_;
    }
    /**
     * <code>repeated string dests = 3;</code>
     */
    public int getDestsCount() {
      return dests_.size();
    }
    /**
     * <code>repeated string dests = 3;</code>
     */
    public java.lang.String getDests(int index) {
      return dests_.get(index);
    }
    /**
     * <code>repeated string dests = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestsBytes(int index) {
      return dests_.getByteString(index);
    }

    public static final int MAX_HOLDING_SECONDS_FIELD_NUMBER = 4;
    private int maxHoldingSeconds_;
    /**
     * <code>uint32 max_holding_seconds = 4;</code>
     */
    public int getMaxHoldingSeconds() {
      return maxHoldingSeconds_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dest_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      for (int i = 0; i < dests_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dests_.getRaw(i));
      }
      if (maxHoldingSeconds_ != 0) {
        output.writeUInt32(4, maxHoldingSeconds_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dest_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dests_.size(); i++) {
          dataSize += computeStringSizeNoTag(dests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDestsList().size();
      }
      if (maxHoldingSeconds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, maxHoldingSeconds_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagesP.ClientToNodeMessage)) {
        return super.equals(obj);
      }
      MessagesP.ClientToNodeMessage other = (MessagesP.ClientToNodeMessage) obj;

      boolean result = true;
      result = result && getDest()
          .equals(other.getDest());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && getDestsList()
          .equals(other.getDestsList());
      result = result && (getMaxHoldingSeconds()
          == other.getMaxHoldingSeconds());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEST_FIELD_NUMBER;
      hash = (53 * hash) + getDest().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      if (getDestsCount() > 0) {
        hash = (37 * hash) + DESTS_FIELD_NUMBER;
        hash = (53 * hash) + getDestsList().hashCode();
      }
      hash = (37 * hash) + MAX_HOLDING_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxHoldingSeconds();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagesP.ClientToNodeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesP.ClientToNodeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagesP.ClientToNodeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesP.ClientToNodeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagesP.ClientToNodeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.ClientToNodeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.ClientToNodeMessage)
        MessagesP.ClientToNodeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesP.internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagesP.internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagesP.ClientToNodeMessage.class, MessagesP.ClientToNodeMessage.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.Messages.ClientToNodeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dest_ = "";

        payload_ = com.google.protobuf.ByteString.EMPTY;

        dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxHoldingSeconds_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagesP.internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_descriptor;
      }

      @java.lang.Override
      public MessagesP.ClientToNodeMessage getDefaultInstanceForType() {
        return MessagesP.ClientToNodeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public MessagesP.ClientToNodeMessage build() {
        MessagesP.ClientToNodeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessagesP.ClientToNodeMessage buildPartial() {
        MessagesP.ClientToNodeMessage result = new MessagesP.ClientToNodeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.dest_ = dest_;
        result.payload_ = payload_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          dests_ = dests_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.dests_ = dests_;
        result.maxHoldingSeconds_ = maxHoldingSeconds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagesP.ClientToNodeMessage) {
          return mergeFrom((MessagesP.ClientToNodeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagesP.ClientToNodeMessage other) {
        if (other == MessagesP.ClientToNodeMessage.getDefaultInstance()) return this;
        if (!other.getDest().isEmpty()) {
          dest_ = other.dest_;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        if (!other.dests_.isEmpty()) {
          if (dests_.isEmpty()) {
            dests_ = other.dests_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDestsIsMutable();
            dests_.addAll(other.dests_);
          }
          onChanged();
        }
        if (other.getMaxHoldingSeconds() != 0) {
          setMaxHoldingSeconds(other.getMaxHoldingSeconds());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagesP.ClientToNodeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagesP.ClientToNodeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object dest_ = "";
      /**
       * <code>string dest = 1;</code>
       */
      public java.lang.String getDest() {
        java.lang.Object ref = dest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dest = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDestBytes() {
        java.lang.Object ref = dest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dest = 1;</code>
       */
      public Builder setDest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dest = 1;</code>
       */
      public Builder clearDest() {
        
        dest_ = getDefaultInstance().getDest();
        onChanged();
        return this;
      }
      /**
       * <code>string dest = 1;</code>
       */
      public Builder setDestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dest_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDestsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          dests_ = new com.google.protobuf.LazyStringArrayList(dests_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDestsList() {
        return dests_.getUnmodifiableView();
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public int getDestsCount() {
        return dests_.size();
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public java.lang.String getDests(int index) {
        return dests_.get(index);
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDestsBytes(int index) {
        return dests_.getByteString(index);
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public Builder setDests(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDestsIsMutable();
        dests_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public Builder addDests(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDestsIsMutable();
        dests_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public Builder addAllDests(
          java.lang.Iterable<java.lang.String> values) {
        ensureDestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dests_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public Builder clearDests() {
        dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 3;</code>
       */
      public Builder addDestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDestsIsMutable();
        dests_.add(value);
        onChanged();
        return this;
      }

      private int maxHoldingSeconds_ ;
      /**
       * <code>uint32 max_holding_seconds = 4;</code>
       */
      public int getMaxHoldingSeconds() {
        return maxHoldingSeconds_;
      }
      /**
       * <code>uint32 max_holding_seconds = 4;</code>
       */
      public Builder setMaxHoldingSeconds(int value) {
        
        maxHoldingSeconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 max_holding_seconds = 4;</code>
       */
      public Builder clearMaxHoldingSeconds() {
        
        maxHoldingSeconds_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.ClientToNodeMessage)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.ClientToNodeMessage)
    private static final MessagesP.ClientToNodeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagesP.ClientToNodeMessage();
    }

    public static MessagesP.ClientToNodeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientToNodeMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClientToNodeMessage>() {
      @java.lang.Override
      public ClientToNodeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientToNodeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientToNodeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientToNodeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessagesP.ClientToNodeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeToClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.NodeToClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string src = 1;</code>
     */
    java.lang.String getSrc();
    /**
     * <code>string src = 1;</code>
     */
    com.google.protobuf.ByteString
        getSrcBytes();

    /**
     * <code>bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.NodeToClientMessage}
   */
  public  static final class NodeToClientMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.NodeToClientMessage)
      NodeToClientMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeToClientMessage.newBuilder() to construct.
    private NodeToClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeToClientMessage() {
      src_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeToClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              src_ = s;
              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagesP.internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagesP.internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagesP.NodeToClientMessage.class, MessagesP.NodeToClientMessage.Builder.class);
    }

    public static final int SRC_FIELD_NUMBER = 1;
    private volatile java.lang.Object src_;
    /**
     * <code>string src = 1;</code>
     */
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        src_ = s;
        return s;
      }
    }
    /**
     * <code>string src = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSrcBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, src_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSrcBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, src_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagesP.NodeToClientMessage)) {
        return super.equals(obj);
      }
      MessagesP.NodeToClientMessage other = (MessagesP.NodeToClientMessage) obj;

      boolean result = true;
      result = result && getSrc()
          .equals(other.getSrc());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRC_FIELD_NUMBER;
      hash = (53 * hash) + getSrc().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagesP.NodeToClientMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesP.NodeToClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesP.NodeToClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesP.NodeToClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagesP.NodeToClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesP.NodeToClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagesP.NodeToClientMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.NodeToClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.NodeToClientMessage)
        MessagesP.NodeToClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesP.internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagesP.internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagesP.NodeToClientMessage.class, MessagesP.NodeToClientMessage.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.Messages.NodeToClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        src_ = "";

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagesP.internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_descriptor;
      }

      @java.lang.Override
      public MessagesP.NodeToClientMessage getDefaultInstanceForType() {
        return MessagesP.NodeToClientMessage.getDefaultInstance();
      }

      @java.lang.Override
      public MessagesP.NodeToClientMessage build() {
        MessagesP.NodeToClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessagesP.NodeToClientMessage buildPartial() {
        MessagesP.NodeToClientMessage result = new MessagesP.NodeToClientMessage(this);
        result.src_ = src_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagesP.NodeToClientMessage) {
          return mergeFrom((MessagesP.NodeToClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagesP.NodeToClientMessage other) {
        if (other == MessagesP.NodeToClientMessage.getDefaultInstance()) return this;
        if (!other.getSrc().isEmpty()) {
          src_ = other.src_;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagesP.NodeToClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagesP.NodeToClientMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object src_ = "";
      /**
       * <code>string src = 1;</code>
       */
      public java.lang.String getSrc() {
        java.lang.Object ref = src_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          src_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string src = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSrcBytes() {
        java.lang.Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string src = 1;</code>
       */
      public Builder setSrc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        src_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string src = 1;</code>
       */
      public Builder clearSrc() {
        
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      /**
       * <code>string src = 1;</code>
       */
      public Builder setSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        src_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.NodeToClientMessage)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.NodeToClientMessage)
    private static final MessagesP.NodeToClientMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagesP.NodeToClientMessage();
    }

    public static MessagesP.NodeToClientMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeToClientMessage>
        PARSER = new com.google.protobuf.AbstractParser<NodeToClientMessage>() {
      @java.lang.Override
      public NodeToClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeToClientMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeToClientMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeToClientMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessagesP.NodeToClientMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*jsmith/nknsdk/network/proto/messages.p" +
      "roto\022\033jsmith.nknsdk.network.proto\"`\n\023Cli" +
      "entToNodeMessage\022\014\n\004dest\030\001 \001(\t\022\017\n\007payloa" +
      "d\030\002 \001(\014\022\r\n\005dests\030\003 \003(\t\022\033\n\023max_holding_se" +
      "conds\030\004 \001(\r\"3\n\023NodeToClientMessage\022\013\n\003sr" +
      "c\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_ClientToNodeMessage_descriptor,
        new java.lang.String[] { "Dest", "Payload", "Dests", "MaxHoldingSeconds", });
    internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_NodeToClientMessage_descriptor,
        new java.lang.String[] { "Src", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
