// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsmith/nknsdk/network/proto/program.proto

package jsmith.nknsdk.network.proto;

public final class ProgramOuterClass {
  private ProgramOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProgramOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.Program)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes code = 1;</code>
     */
    com.google.protobuf.ByteString getCode();

    /**
     * <code>bytes parameter = 2;</code>
     */
    com.google.protobuf.ByteString getParameter();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.Program}
   */
  public  static final class Program extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.Program)
      ProgramOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Program.newBuilder() to construct.
    private Program(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Program() {
      code_ = com.google.protobuf.ByteString.EMPTY;
      parameter_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Program(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              code_ = input.readBytes();
              break;
            }
            case 18: {

              parameter_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jsmith.nknsdk.network.proto.ProgramOuterClass.internal_static_jsmith_nknsdk_network_proto_Program_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jsmith.nknsdk.network.proto.ProgramOuterClass.internal_static_jsmith_nknsdk_network_proto_Program_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jsmith.nknsdk.network.proto.ProgramOuterClass.Program.class, jsmith.nknsdk.network.proto.ProgramOuterClass.Program.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString code_;
    /**
     * <code>bytes code = 1;</code>
     */
    public com.google.protobuf.ByteString getCode() {
      return code_;
    }

    public static final int PARAMETER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString parameter_;
    /**
     * <code>bytes parameter = 2;</code>
     */
    public com.google.protobuf.ByteString getParameter() {
      return parameter_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!code_.isEmpty()) {
        output.writeBytes(1, code_);
      }
      if (!parameter_.isEmpty()) {
        output.writeBytes(2, parameter_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, code_);
      }
      if (!parameter_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, parameter_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jsmith.nknsdk.network.proto.ProgramOuterClass.Program)) {
        return super.equals(obj);
      }
      jsmith.nknsdk.network.proto.ProgramOuterClass.Program other = (jsmith.nknsdk.network.proto.ProgramOuterClass.Program) obj;

      boolean result = true;
      result = result && getCode()
          .equals(other.getCode());
      result = result && getParameter()
          .equals(other.getParameter());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getParameter().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jsmith.nknsdk.network.proto.ProgramOuterClass.Program prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.Program}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.Program)
        jsmith.nknsdk.network.proto.ProgramOuterClass.ProgramOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jsmith.nknsdk.network.proto.ProgramOuterClass.internal_static_jsmith_nknsdk_network_proto_Program_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jsmith.nknsdk.network.proto.ProgramOuterClass.internal_static_jsmith_nknsdk_network_proto_Program_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jsmith.nknsdk.network.proto.ProgramOuterClass.Program.class, jsmith.nknsdk.network.proto.ProgramOuterClass.Program.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.ProgramOuterClass.Program.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = com.google.protobuf.ByteString.EMPTY;

        parameter_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jsmith.nknsdk.network.proto.ProgramOuterClass.internal_static_jsmith_nknsdk_network_proto_Program_descriptor;
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.ProgramOuterClass.Program getDefaultInstanceForType() {
        return jsmith.nknsdk.network.proto.ProgramOuterClass.Program.getDefaultInstance();
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.ProgramOuterClass.Program build() {
        jsmith.nknsdk.network.proto.ProgramOuterClass.Program result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.ProgramOuterClass.Program buildPartial() {
        jsmith.nknsdk.network.proto.ProgramOuterClass.Program result = new jsmith.nknsdk.network.proto.ProgramOuterClass.Program(this);
        result.code_ = code_;
        result.parameter_ = parameter_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jsmith.nknsdk.network.proto.ProgramOuterClass.Program) {
          return mergeFrom((jsmith.nknsdk.network.proto.ProgramOuterClass.Program)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jsmith.nknsdk.network.proto.ProgramOuterClass.Program other) {
        if (other == jsmith.nknsdk.network.proto.ProgramOuterClass.Program.getDefaultInstance()) return this;
        if (other.getCode() != com.google.protobuf.ByteString.EMPTY) {
          setCode(other.getCode());
        }
        if (other.getParameter() != com.google.protobuf.ByteString.EMPTY) {
          setParameter(other.getParameter());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jsmith.nknsdk.network.proto.ProgramOuterClass.Program parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jsmith.nknsdk.network.proto.ProgramOuterClass.Program) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString code_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes code = 1;</code>
       */
      public com.google.protobuf.ByteString getCode() {
        return code_;
      }
      /**
       * <code>bytes code = 1;</code>
       */
      public Builder setCode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString parameter_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes parameter = 2;</code>
       */
      public com.google.protobuf.ByteString getParameter() {
        return parameter_;
      }
      /**
       * <code>bytes parameter = 2;</code>
       */
      public Builder setParameter(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes parameter = 2;</code>
       */
      public Builder clearParameter() {
        
        parameter_ = getDefaultInstance().getParameter();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.Program)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.Program)
    private static final jsmith.nknsdk.network.proto.ProgramOuterClass.Program DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jsmith.nknsdk.network.proto.ProgramOuterClass.Program();
    }

    public static jsmith.nknsdk.network.proto.ProgramOuterClass.Program getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Program>
        PARSER = new com.google.protobuf.AbstractParser<Program>() {
      @java.lang.Override
      public Program parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Program(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Program> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Program> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jsmith.nknsdk.network.proto.ProgramOuterClass.Program getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_Program_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_Program_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)jsmith/nknsdk/network/proto/program.pr" +
      "oto\022\033jsmith.nknsdk.network.proto\"*\n\007Prog" +
      "ram\022\014\n\004code\030\001 \001(\014\022\021\n\tparameter\030\002 \001(\014b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jsmith_nknsdk_network_proto_Program_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jsmith_nknsdk_network_proto_Program_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_Program_descriptor,
        new java.lang.String[] { "Code", "Parameter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
