// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsmith/nknsdk/network/proto/sigchainP.proto

package jsmith.nknsdk.network.proto;

public final class SigchainP {
  private SigchainP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code jsmith.nknsdk.network.proto.SigAlgo}
   */
  public enum SigAlgo
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SIGNATURE = 0;</code>
     */
    SIGNATURE(0),
    /**
     * <code>VRF = 1;</code>
     */
    VRF(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SIGNATURE = 0;</code>
     */
    public static final int SIGNATURE_VALUE = 0;
    /**
     * <code>VRF = 1;</code>
     */
    public static final int VRF_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SigAlgo valueOf(int value) {
      return forNumber(value);
    }

    public static SigAlgo forNumber(int value) {
      switch (value) {
        case 0: return SIGNATURE;
        case 1: return VRF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SigAlgo>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SigAlgo> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SigAlgo>() {
            public SigAlgo findValueByNumber(int number) {
              return SigAlgo.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jsmith.nknsdk.network.proto.SigchainP.getDescriptor().getEnumTypes().get(0);
    }

    private static final SigAlgo[] VALUES = values();

    public static SigAlgo valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SigAlgo(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jsmith.nknsdk.network.proto.SigAlgo)
  }

  public interface SigChainElemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.SigChainElem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>bytes next_pubkey = 2;</code>
     */
    com.google.protobuf.ByteString getNextPubkey();

    /**
     * <code>bool mining = 3;</code>
     */
    boolean getMining();

    /**
     * <code>bytes signature = 4;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
     */
    int getSigAlgoValue();
    /**
     * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
     */
    jsmith.nknsdk.network.proto.SigchainP.SigAlgo getSigAlgo();

    /**
     * <code>bytes vrf = 6;</code>
     */
    com.google.protobuf.ByteString getVrf();

    /**
     * <code>bytes proof = 7;</code>
     */
    com.google.protobuf.ByteString getProof();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.SigChainElem}
   */
  public  static final class SigChainElem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.SigChainElem)
      SigChainElemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigChainElem.newBuilder() to construct.
    private SigChainElem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigChainElem() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      nextPubkey_ = com.google.protobuf.ByteString.EMPTY;
      mining_ = false;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      sigAlgo_ = 0;
      vrf_ = com.google.protobuf.ByteString.EMPTY;
      proof_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigChainElem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              id_ = input.readBytes();
              break;
            }
            case 18: {

              nextPubkey_ = input.readBytes();
              break;
            }
            case 24: {

              mining_ = input.readBool();
              break;
            }
            case 34: {

              signature_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              sigAlgo_ = rawValue;
              break;
            }
            case 50: {

              vrf_ = input.readBytes();
              break;
            }
            case 58: {

              proof_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChainElem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChainElem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jsmith.nknsdk.network.proto.SigchainP.SigChainElem.class, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int NEXT_PUBKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString nextPubkey_;
    /**
     * <code>bytes next_pubkey = 2;</code>
     */
    public com.google.protobuf.ByteString getNextPubkey() {
      return nextPubkey_;
    }

    public static final int MINING_FIELD_NUMBER = 3;
    private boolean mining_;
    /**
     * <code>bool mining = 3;</code>
     */
    public boolean getMining() {
      return mining_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 4;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int SIG_ALGO_FIELD_NUMBER = 5;
    private int sigAlgo_;
    /**
     * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
     */
    public int getSigAlgoValue() {
      return sigAlgo_;
    }
    /**
     * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
     */
    public jsmith.nknsdk.network.proto.SigchainP.SigAlgo getSigAlgo() {
      @SuppressWarnings("deprecation")
      jsmith.nknsdk.network.proto.SigchainP.SigAlgo result = jsmith.nknsdk.network.proto.SigchainP.SigAlgo.valueOf(sigAlgo_);
      return result == null ? jsmith.nknsdk.network.proto.SigchainP.SigAlgo.UNRECOGNIZED : result;
    }

    public static final int VRF_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString vrf_;
    /**
     * <code>bytes vrf = 6;</code>
     */
    public com.google.protobuf.ByteString getVrf() {
      return vrf_;
    }

    public static final int PROOF_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString proof_;
    /**
     * <code>bytes proof = 7;</code>
     */
    public com.google.protobuf.ByteString getProof() {
      return proof_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      if (!nextPubkey_.isEmpty()) {
        output.writeBytes(2, nextPubkey_);
      }
      if (mining_ != false) {
        output.writeBool(3, mining_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(4, signature_);
      }
      if (sigAlgo_ != jsmith.nknsdk.network.proto.SigchainP.SigAlgo.SIGNATURE.getNumber()) {
        output.writeEnum(5, sigAlgo_);
      }
      if (!vrf_.isEmpty()) {
        output.writeBytes(6, vrf_);
      }
      if (!proof_.isEmpty()) {
        output.writeBytes(7, proof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (!nextPubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, nextPubkey_);
      }
      if (mining_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, mining_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, signature_);
      }
      if (sigAlgo_ != jsmith.nknsdk.network.proto.SigchainP.SigAlgo.SIGNATURE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, sigAlgo_);
      }
      if (!vrf_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, vrf_);
      }
      if (!proof_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, proof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jsmith.nknsdk.network.proto.SigchainP.SigChainElem)) {
        return super.equals(obj);
      }
      jsmith.nknsdk.network.proto.SigchainP.SigChainElem other = (jsmith.nknsdk.network.proto.SigchainP.SigChainElem) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getNextPubkey()
          .equals(other.getNextPubkey());
      result = result && (getMining()
          == other.getMining());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && sigAlgo_ == other.sigAlgo_;
      result = result && getVrf()
          .equals(other.getVrf());
      result = result && getProof()
          .equals(other.getProof());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NEXT_PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getNextPubkey().hashCode();
      hash = (37 * hash) + MINING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMining());
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + SIG_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + sigAlgo_;
      hash = (37 * hash) + VRF_FIELD_NUMBER;
      hash = (53 * hash) + getVrf().hashCode();
      hash = (37 * hash) + PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getProof().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jsmith.nknsdk.network.proto.SigchainP.SigChainElem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.SigChainElem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.SigChainElem)
        jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChainElem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChainElem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jsmith.nknsdk.network.proto.SigchainP.SigChainElem.class, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.SigchainP.SigChainElem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;

        nextPubkey_ = com.google.protobuf.ByteString.EMPTY;

        mining_ = false;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        sigAlgo_ = 0;

        vrf_ = com.google.protobuf.ByteString.EMPTY;

        proof_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChainElem_descriptor;
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem getDefaultInstanceForType() {
        return jsmith.nknsdk.network.proto.SigchainP.SigChainElem.getDefaultInstance();
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem build() {
        jsmith.nknsdk.network.proto.SigchainP.SigChainElem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem buildPartial() {
        jsmith.nknsdk.network.proto.SigchainP.SigChainElem result = new jsmith.nknsdk.network.proto.SigchainP.SigChainElem(this);
        result.id_ = id_;
        result.nextPubkey_ = nextPubkey_;
        result.mining_ = mining_;
        result.signature_ = signature_;
        result.sigAlgo_ = sigAlgo_;
        result.vrf_ = vrf_;
        result.proof_ = proof_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jsmith.nknsdk.network.proto.SigchainP.SigChainElem) {
          return mergeFrom((jsmith.nknsdk.network.proto.SigchainP.SigChainElem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jsmith.nknsdk.network.proto.SigchainP.SigChainElem other) {
        if (other == jsmith.nknsdk.network.proto.SigchainP.SigChainElem.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (other.getNextPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setNextPubkey(other.getNextPubkey());
        }
        if (other.getMining() != false) {
          setMining(other.getMining());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.sigAlgo_ != 0) {
          setSigAlgoValue(other.getSigAlgoValue());
        }
        if (other.getVrf() != com.google.protobuf.ByteString.EMPTY) {
          setVrf(other.getVrf());
        }
        if (other.getProof() != com.google.protobuf.ByteString.EMPTY) {
          setProof(other.getProof());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jsmith.nknsdk.network.proto.SigchainP.SigChainElem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jsmith.nknsdk.network.proto.SigchainP.SigChainElem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nextPubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes next_pubkey = 2;</code>
       */
      public com.google.protobuf.ByteString getNextPubkey() {
        return nextPubkey_;
      }
      /**
       * <code>bytes next_pubkey = 2;</code>
       */
      public Builder setNextPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nextPubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes next_pubkey = 2;</code>
       */
      public Builder clearNextPubkey() {
        
        nextPubkey_ = getDefaultInstance().getNextPubkey();
        onChanged();
        return this;
      }

      private boolean mining_ ;
      /**
       * <code>bool mining = 3;</code>
       */
      public boolean getMining() {
        return mining_;
      }
      /**
       * <code>bool mining = 3;</code>
       */
      public Builder setMining(boolean value) {
        
        mining_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool mining = 3;</code>
       */
      public Builder clearMining() {
        
        mining_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 4;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 4;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 4;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private int sigAlgo_ = 0;
      /**
       * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
       */
      public int getSigAlgoValue() {
        return sigAlgo_;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
       */
      public Builder setSigAlgoValue(int value) {
        sigAlgo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
       */
      public jsmith.nknsdk.network.proto.SigchainP.SigAlgo getSigAlgo() {
        @SuppressWarnings("deprecation")
        jsmith.nknsdk.network.proto.SigchainP.SigAlgo result = jsmith.nknsdk.network.proto.SigchainP.SigAlgo.valueOf(sigAlgo_);
        return result == null ? jsmith.nknsdk.network.proto.SigchainP.SigAlgo.UNRECOGNIZED : result;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
       */
      public Builder setSigAlgo(jsmith.nknsdk.network.proto.SigchainP.SigAlgo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sigAlgo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.SigAlgo sig_algo = 5;</code>
       */
      public Builder clearSigAlgo() {
        
        sigAlgo_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString vrf_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes vrf = 6;</code>
       */
      public com.google.protobuf.ByteString getVrf() {
        return vrf_;
      }
      /**
       * <code>bytes vrf = 6;</code>
       */
      public Builder setVrf(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vrf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes vrf = 6;</code>
       */
      public Builder clearVrf() {
        
        vrf_ = getDefaultInstance().getVrf();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString proof_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes proof = 7;</code>
       */
      public com.google.protobuf.ByteString getProof() {
        return proof_;
      }
      /**
       * <code>bytes proof = 7;</code>
       */
      public Builder setProof(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes proof = 7;</code>
       */
      public Builder clearProof() {
        
        proof_ = getDefaultInstance().getProof();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.SigChainElem)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.SigChainElem)
    private static final jsmith.nknsdk.network.proto.SigchainP.SigChainElem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jsmith.nknsdk.network.proto.SigchainP.SigChainElem();
    }

    public static jsmith.nknsdk.network.proto.SigchainP.SigChainElem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigChainElem>
        PARSER = new com.google.protobuf.AbstractParser<SigChainElem>() {
      @java.lang.Override
      public SigChainElem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigChainElem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigChainElem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigChainElem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jsmith.nknsdk.network.proto.SigchainP.SigChainElem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigChainOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.SigChain)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 nonce = 1;</code>
     */
    int getNonce();

    /**
     * <code>uint32 data_size = 2;</code>
     */
    int getDataSize();

    /**
     * <code>bytes block_hash = 3;</code>
     */
    com.google.protobuf.ByteString getBlockHash();

    /**
     * <code>bytes src_id = 4;</code>
     */
    com.google.protobuf.ByteString getSrcId();

    /**
     * <code>bytes src_pubkey = 5;</code>
     */
    com.google.protobuf.ByteString getSrcPubkey();

    /**
     * <code>bytes dest_id = 6;</code>
     */
    com.google.protobuf.ByteString getDestId();

    /**
     * <code>bytes dest_pubkey = 7;</code>
     */
    com.google.protobuf.ByteString getDestPubkey();

    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    java.util.List<jsmith.nknsdk.network.proto.SigchainP.SigChainElem> 
        getElemsList();
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    jsmith.nknsdk.network.proto.SigchainP.SigChainElem getElems(int index);
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    int getElemsCount();
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    java.util.List<? extends jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder> 
        getElemsOrBuilderList();
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder getElemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.SigChain}
   */
  public  static final class SigChain extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.SigChain)
      SigChainOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigChain.newBuilder() to construct.
    private SigChain(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigChain() {
      nonce_ = 0;
      dataSize_ = 0;
      blockHash_ = com.google.protobuf.ByteString.EMPTY;
      srcId_ = com.google.protobuf.ByteString.EMPTY;
      srcPubkey_ = com.google.protobuf.ByteString.EMPTY;
      destId_ = com.google.protobuf.ByteString.EMPTY;
      destPubkey_ = com.google.protobuf.ByteString.EMPTY;
      elems_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigChain(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nonce_ = input.readUInt32();
              break;
            }
            case 16: {

              dataSize_ = input.readUInt32();
              break;
            }
            case 26: {

              blockHash_ = input.readBytes();
              break;
            }
            case 34: {

              srcId_ = input.readBytes();
              break;
            }
            case 42: {

              srcPubkey_ = input.readBytes();
              break;
            }
            case 50: {

              destId_ = input.readBytes();
              break;
            }
            case 58: {

              destPubkey_ = input.readBytes();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                elems_ = new java.util.ArrayList<jsmith.nknsdk.network.proto.SigchainP.SigChainElem>();
                mutable_bitField0_ |= 0x00000080;
              }
              elems_.add(
                  input.readMessage(jsmith.nknsdk.network.proto.SigchainP.SigChainElem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          elems_ = java.util.Collections.unmodifiableList(elems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChain_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jsmith.nknsdk.network.proto.SigchainP.SigChain.class, jsmith.nknsdk.network.proto.SigchainP.SigChain.Builder.class);
    }

    private int bitField0_;
    public static final int NONCE_FIELD_NUMBER = 1;
    private int nonce_;
    /**
     * <code>uint32 nonce = 1;</code>
     */
    public int getNonce() {
      return nonce_;
    }

    public static final int DATA_SIZE_FIELD_NUMBER = 2;
    private int dataSize_;
    /**
     * <code>uint32 data_size = 2;</code>
     */
    public int getDataSize() {
      return dataSize_;
    }

    public static final int BLOCK_HASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString blockHash_;
    /**
     * <code>bytes block_hash = 3;</code>
     */
    public com.google.protobuf.ByteString getBlockHash() {
      return blockHash_;
    }

    public static final int SRC_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString srcId_;
    /**
     * <code>bytes src_id = 4;</code>
     */
    public com.google.protobuf.ByteString getSrcId() {
      return srcId_;
    }

    public static final int SRC_PUBKEY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString srcPubkey_;
    /**
     * <code>bytes src_pubkey = 5;</code>
     */
    public com.google.protobuf.ByteString getSrcPubkey() {
      return srcPubkey_;
    }

    public static final int DEST_ID_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString destId_;
    /**
     * <code>bytes dest_id = 6;</code>
     */
    public com.google.protobuf.ByteString getDestId() {
      return destId_;
    }

    public static final int DEST_PUBKEY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString destPubkey_;
    /**
     * <code>bytes dest_pubkey = 7;</code>
     */
    public com.google.protobuf.ByteString getDestPubkey() {
      return destPubkey_;
    }

    public static final int ELEMS_FIELD_NUMBER = 8;
    private java.util.List<jsmith.nknsdk.network.proto.SigchainP.SigChainElem> elems_;
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    public java.util.List<jsmith.nknsdk.network.proto.SigchainP.SigChainElem> getElemsList() {
      return elems_;
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    public java.util.List<? extends jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder> 
        getElemsOrBuilderList() {
      return elems_;
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    public int getElemsCount() {
      return elems_.size();
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    public jsmith.nknsdk.network.proto.SigchainP.SigChainElem getElems(int index) {
      return elems_.get(index);
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
     */
    public jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder getElemsOrBuilder(
        int index) {
      return elems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nonce_ != 0) {
        output.writeUInt32(1, nonce_);
      }
      if (dataSize_ != 0) {
        output.writeUInt32(2, dataSize_);
      }
      if (!blockHash_.isEmpty()) {
        output.writeBytes(3, blockHash_);
      }
      if (!srcId_.isEmpty()) {
        output.writeBytes(4, srcId_);
      }
      if (!srcPubkey_.isEmpty()) {
        output.writeBytes(5, srcPubkey_);
      }
      if (!destId_.isEmpty()) {
        output.writeBytes(6, destId_);
      }
      if (!destPubkey_.isEmpty()) {
        output.writeBytes(7, destPubkey_);
      }
      for (int i = 0; i < elems_.size(); i++) {
        output.writeMessage(8, elems_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nonce_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, nonce_);
      }
      if (dataSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, dataSize_);
      }
      if (!blockHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, blockHash_);
      }
      if (!srcId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, srcId_);
      }
      if (!srcPubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, srcPubkey_);
      }
      if (!destId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, destId_);
      }
      if (!destPubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, destPubkey_);
      }
      for (int i = 0; i < elems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, elems_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jsmith.nknsdk.network.proto.SigchainP.SigChain)) {
        return super.equals(obj);
      }
      jsmith.nknsdk.network.proto.SigchainP.SigChain other = (jsmith.nknsdk.network.proto.SigchainP.SigChain) obj;

      boolean result = true;
      result = result && (getNonce()
          == other.getNonce());
      result = result && (getDataSize()
          == other.getDataSize());
      result = result && getBlockHash()
          .equals(other.getBlockHash());
      result = result && getSrcId()
          .equals(other.getSrcId());
      result = result && getSrcPubkey()
          .equals(other.getSrcPubkey());
      result = result && getDestId()
          .equals(other.getDestId());
      result = result && getDestPubkey()
          .equals(other.getDestPubkey());
      result = result && getElemsList()
          .equals(other.getElemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce();
      hash = (37 * hash) + DATA_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getDataSize();
      hash = (37 * hash) + BLOCK_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHash().hashCode();
      hash = (37 * hash) + SRC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcId().hashCode();
      hash = (37 * hash) + SRC_PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSrcPubkey().hashCode();
      hash = (37 * hash) + DEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDestId().hashCode();
      hash = (37 * hash) + DEST_PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getDestPubkey().hashCode();
      if (getElemsCount() > 0) {
        hash = (37 * hash) + ELEMS_FIELD_NUMBER;
        hash = (53 * hash) + getElemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jsmith.nknsdk.network.proto.SigchainP.SigChain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jsmith.nknsdk.network.proto.SigchainP.SigChain prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.SigChain}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.SigChain)
        jsmith.nknsdk.network.proto.SigchainP.SigChainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChain_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jsmith.nknsdk.network.proto.SigchainP.SigChain.class, jsmith.nknsdk.network.proto.SigchainP.SigChain.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.SigchainP.SigChain.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getElemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nonce_ = 0;

        dataSize_ = 0;

        blockHash_ = com.google.protobuf.ByteString.EMPTY;

        srcId_ = com.google.protobuf.ByteString.EMPTY;

        srcPubkey_ = com.google.protobuf.ByteString.EMPTY;

        destId_ = com.google.protobuf.ByteString.EMPTY;

        destPubkey_ = com.google.protobuf.ByteString.EMPTY;

        if (elemsBuilder_ == null) {
          elems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          elemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jsmith.nknsdk.network.proto.SigchainP.internal_static_jsmith_nknsdk_network_proto_SigChain_descriptor;
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.SigchainP.SigChain getDefaultInstanceForType() {
        return jsmith.nknsdk.network.proto.SigchainP.SigChain.getDefaultInstance();
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.SigchainP.SigChain build() {
        jsmith.nknsdk.network.proto.SigchainP.SigChain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jsmith.nknsdk.network.proto.SigchainP.SigChain buildPartial() {
        jsmith.nknsdk.network.proto.SigchainP.SigChain result = new jsmith.nknsdk.network.proto.SigchainP.SigChain(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.nonce_ = nonce_;
        result.dataSize_ = dataSize_;
        result.blockHash_ = blockHash_;
        result.srcId_ = srcId_;
        result.srcPubkey_ = srcPubkey_;
        result.destId_ = destId_;
        result.destPubkey_ = destPubkey_;
        if (elemsBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            elems_ = java.util.Collections.unmodifiableList(elems_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.elems_ = elems_;
        } else {
          result.elems_ = elemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jsmith.nknsdk.network.proto.SigchainP.SigChain) {
          return mergeFrom((jsmith.nknsdk.network.proto.SigchainP.SigChain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jsmith.nknsdk.network.proto.SigchainP.SigChain other) {
        if (other == jsmith.nknsdk.network.proto.SigchainP.SigChain.getDefaultInstance()) return this;
        if (other.getNonce() != 0) {
          setNonce(other.getNonce());
        }
        if (other.getDataSize() != 0) {
          setDataSize(other.getDataSize());
        }
        if (other.getBlockHash() != com.google.protobuf.ByteString.EMPTY) {
          setBlockHash(other.getBlockHash());
        }
        if (other.getSrcId() != com.google.protobuf.ByteString.EMPTY) {
          setSrcId(other.getSrcId());
        }
        if (other.getSrcPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setSrcPubkey(other.getSrcPubkey());
        }
        if (other.getDestId() != com.google.protobuf.ByteString.EMPTY) {
          setDestId(other.getDestId());
        }
        if (other.getDestPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setDestPubkey(other.getDestPubkey());
        }
        if (elemsBuilder_ == null) {
          if (!other.elems_.isEmpty()) {
            if (elems_.isEmpty()) {
              elems_ = other.elems_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureElemsIsMutable();
              elems_.addAll(other.elems_);
            }
            onChanged();
          }
        } else {
          if (!other.elems_.isEmpty()) {
            if (elemsBuilder_.isEmpty()) {
              elemsBuilder_.dispose();
              elemsBuilder_ = null;
              elems_ = other.elems_;
              bitField0_ = (bitField0_ & ~0x00000080);
              elemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getElemsFieldBuilder() : null;
            } else {
              elemsBuilder_.addAllMessages(other.elems_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jsmith.nknsdk.network.proto.SigchainP.SigChain parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jsmith.nknsdk.network.proto.SigchainP.SigChain) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int nonce_ ;
      /**
       * <code>uint32 nonce = 1;</code>
       */
      public int getNonce() {
        return nonce_;
      }
      /**
       * <code>uint32 nonce = 1;</code>
       */
      public Builder setNonce(int value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 nonce = 1;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0;
        onChanged();
        return this;
      }

      private int dataSize_ ;
      /**
       * <code>uint32 data_size = 2;</code>
       */
      public int getDataSize() {
        return dataSize_;
      }
      /**
       * <code>uint32 data_size = 2;</code>
       */
      public Builder setDataSize(int value) {
        
        dataSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 data_size = 2;</code>
       */
      public Builder clearDataSize() {
        
        dataSize_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString blockHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes block_hash = 3;</code>
       */
      public com.google.protobuf.ByteString getBlockHash() {
        return blockHash_;
      }
      /**
       * <code>bytes block_hash = 3;</code>
       */
      public Builder setBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blockHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes block_hash = 3;</code>
       */
      public Builder clearBlockHash() {
        
        blockHash_ = getDefaultInstance().getBlockHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString srcId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes src_id = 4;</code>
       */
      public com.google.protobuf.ByteString getSrcId() {
        return srcId_;
      }
      /**
       * <code>bytes src_id = 4;</code>
       */
      public Builder setSrcId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes src_id = 4;</code>
       */
      public Builder clearSrcId() {
        
        srcId_ = getDefaultInstance().getSrcId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString srcPubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes src_pubkey = 5;</code>
       */
      public com.google.protobuf.ByteString getSrcPubkey() {
        return srcPubkey_;
      }
      /**
       * <code>bytes src_pubkey = 5;</code>
       */
      public Builder setSrcPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcPubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes src_pubkey = 5;</code>
       */
      public Builder clearSrcPubkey() {
        
        srcPubkey_ = getDefaultInstance().getSrcPubkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString destId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes dest_id = 6;</code>
       */
      public com.google.protobuf.ByteString getDestId() {
        return destId_;
      }
      /**
       * <code>bytes dest_id = 6;</code>
       */
      public Builder setDestId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes dest_id = 6;</code>
       */
      public Builder clearDestId() {
        
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString destPubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes dest_pubkey = 7;</code>
       */
      public com.google.protobuf.ByteString getDestPubkey() {
        return destPubkey_;
      }
      /**
       * <code>bytes dest_pubkey = 7;</code>
       */
      public Builder setDestPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destPubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes dest_pubkey = 7;</code>
       */
      public Builder clearDestPubkey() {
        
        destPubkey_ = getDefaultInstance().getDestPubkey();
        onChanged();
        return this;
      }

      private java.util.List<jsmith.nknsdk.network.proto.SigchainP.SigChainElem> elems_ =
        java.util.Collections.emptyList();
      private void ensureElemsIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          elems_ = new java.util.ArrayList<jsmith.nknsdk.network.proto.SigchainP.SigChainElem>(elems_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jsmith.nknsdk.network.proto.SigchainP.SigChainElem, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder, jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder> elemsBuilder_;

      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public java.util.List<jsmith.nknsdk.network.proto.SigchainP.SigChainElem> getElemsList() {
        if (elemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(elems_);
        } else {
          return elemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public int getElemsCount() {
        if (elemsBuilder_ == null) {
          return elems_.size();
        } else {
          return elemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem getElems(int index) {
        if (elemsBuilder_ == null) {
          return elems_.get(index);
        } else {
          return elemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder setElems(
          int index, jsmith.nknsdk.network.proto.SigchainP.SigChainElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.set(index, value);
          onChanged();
        } else {
          elemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder setElems(
          int index, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.set(index, builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder addElems(jsmith.nknsdk.network.proto.SigchainP.SigChainElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.add(value);
          onChanged();
        } else {
          elemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder addElems(
          int index, jsmith.nknsdk.network.proto.SigchainP.SigChainElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.add(index, value);
          onChanged();
        } else {
          elemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder addElems(
          jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.add(builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder addElems(
          int index, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.add(index, builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder addAllElems(
          java.lang.Iterable<? extends jsmith.nknsdk.network.proto.SigchainP.SigChainElem> values) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, elems_);
          onChanged();
        } else {
          elemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder clearElems() {
        if (elemsBuilder_ == null) {
          elems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          elemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public Builder removeElems(int index) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.remove(index);
          onChanged();
        } else {
          elemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder getElemsBuilder(
          int index) {
        return getElemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder getElemsOrBuilder(
          int index) {
        if (elemsBuilder_ == null) {
          return elems_.get(index);  } else {
          return elemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public java.util.List<? extends jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder> 
           getElemsOrBuilderList() {
        if (elemsBuilder_ != null) {
          return elemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(elems_);
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder addElemsBuilder() {
        return getElemsFieldBuilder().addBuilder(
            jsmith.nknsdk.network.proto.SigchainP.SigChainElem.getDefaultInstance());
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder addElemsBuilder(
          int index) {
        return getElemsFieldBuilder().addBuilder(
            index, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.getDefaultInstance());
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.SigChainElem elems = 8;</code>
       */
      public java.util.List<jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder> 
           getElemsBuilderList() {
        return getElemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jsmith.nknsdk.network.proto.SigchainP.SigChainElem, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder, jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder> 
          getElemsFieldBuilder() {
        if (elemsBuilder_ == null) {
          elemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jsmith.nknsdk.network.proto.SigchainP.SigChainElem, jsmith.nknsdk.network.proto.SigchainP.SigChainElem.Builder, jsmith.nknsdk.network.proto.SigchainP.SigChainElemOrBuilder>(
                  elems_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          elems_ = null;
        }
        return elemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.SigChain)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.SigChain)
    private static final jsmith.nknsdk.network.proto.SigchainP.SigChain DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jsmith.nknsdk.network.proto.SigchainP.SigChain();
    }

    public static jsmith.nknsdk.network.proto.SigchainP.SigChain getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigChain>
        PARSER = new com.google.protobuf.AbstractParser<SigChain>() {
      @java.lang.Override
      public SigChain parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigChain(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigChain> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigChain> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jsmith.nknsdk.network.proto.SigchainP.SigChain getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_SigChainElem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_SigChainElem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_SigChain_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_SigChain_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+jsmith/nknsdk/network/proto/sigchainP." +
      "proto\022\033jsmith.nknsdk.network.proto\"\246\001\n\014S" +
      "igChainElem\022\n\n\002id\030\001 \001(\014\022\023\n\013next_pubkey\030\002" +
      " \001(\014\022\016\n\006mining\030\003 \001(\010\022\021\n\tsignature\030\004 \001(\014\022" +
      "6\n\010sig_algo\030\005 \001(\0162$.jsmith.nknsdk.networ" +
      "k.proto.SigAlgo\022\013\n\003vrf\030\006 \001(\014\022\r\n\005proof\030\007 " +
      "\001(\014\"\304\001\n\010SigChain\022\r\n\005nonce\030\001 \001(\r\022\021\n\tdata_" +
      "size\030\002 \001(\r\022\022\n\nblock_hash\030\003 \001(\014\022\016\n\006src_id" +
      "\030\004 \001(\014\022\022\n\nsrc_pubkey\030\005 \001(\014\022\017\n\007dest_id\030\006 " +
      "\001(\014\022\023\n\013dest_pubkey\030\007 \001(\014\0228\n\005elems\030\010 \003(\0132" +
      ").jsmith.nknsdk.network.proto.SigChainEl" +
      "em*!\n\007SigAlgo\022\r\n\tSIGNATURE\020\000\022\007\n\003VRF\020\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jsmith_nknsdk_network_proto_SigChainElem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jsmith_nknsdk_network_proto_SigChainElem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_SigChainElem_descriptor,
        new java.lang.String[] { "Id", "NextPubkey", "Mining", "Signature", "SigAlgo", "Vrf", "Proof", });
    internal_static_jsmith_nknsdk_network_proto_SigChain_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jsmith_nknsdk_network_proto_SigChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_SigChain_descriptor,
        new java.lang.String[] { "Nonce", "DataSize", "BlockHash", "SrcId", "SrcPubkey", "DestId", "DestPubkey", "Elems", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
