// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsmith/nknsdk/network/proto/transaction.proto

package jsmith.nknsdk.network.proto;

public final class TransactionP {
  private TransactionP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnsignedTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.UnsignedTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
     */
    boolean hasPayload();
    /**
     * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
     */
    TransactionpayloadP.TransactionPayload getPayload();
    /**
     * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
     */
    TransactionpayloadP.TransactionPayloadOrBuilder getPayloadOrBuilder();

    /**
     * <code>uint64 nonce = 2;</code>
     */
    long getNonce();

    /**
     * <code>int64 fee = 3;</code>
     */
    long getFee();

    /**
     * <code>bytes attributes = 4;</code>
     */
    com.google.protobuf.ByteString getAttributes();
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.UnsignedTx}
   */
  public  static final class UnsignedTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.UnsignedTx)
      UnsignedTxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnsignedTx.newBuilder() to construct.
    private UnsignedTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnsignedTx() {
      nonce_ = 0L;
      fee_ = 0L;
      attributes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnsignedTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              TransactionpayloadP.TransactionPayload.Builder subBuilder = null;
              if (payload_ != null) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(TransactionpayloadP.TransactionPayload.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              nonce_ = input.readUInt64();
              break;
            }
            case 24: {

              fee_ = input.readInt64();
              break;
            }
            case 34: {

              attributes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransactionP.internal_static_jsmith_nknsdk_network_proto_UnsignedTx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransactionP.internal_static_jsmith_nknsdk_network_proto_UnsignedTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransactionP.UnsignedTx.class, TransactionP.UnsignedTx.Builder.class);
    }

    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private TransactionpayloadP.TransactionPayload payload_;
    /**
     * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
     */
    public boolean hasPayload() {
      return payload_ != null;
    }
    /**
     * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
     */
    public TransactionpayloadP.TransactionPayload getPayload() {
      return payload_ == null ? TransactionpayloadP.TransactionPayload.getDefaultInstance() : payload_;
    }
    /**
     * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
     */
    public TransactionpayloadP.TransactionPayloadOrBuilder getPayloadOrBuilder() {
      return getPayload();
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private long nonce_;
    /**
     * <code>uint64 nonce = 2;</code>
     */
    public long getNonce() {
      return nonce_;
    }

    public static final int FEE_FIELD_NUMBER = 3;
    private long fee_;
    /**
     * <code>int64 fee = 3;</code>
     */
    public long getFee() {
      return fee_;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString attributes_;
    /**
     * <code>bytes attributes = 4;</code>
     */
    public com.google.protobuf.ByteString getAttributes() {
      return attributes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payload_ != null) {
        output.writeMessage(1, getPayload());
      }
      if (nonce_ != 0L) {
        output.writeUInt64(2, nonce_);
      }
      if (fee_ != 0L) {
        output.writeInt64(3, fee_);
      }
      if (!attributes_.isEmpty()) {
        output.writeBytes(4, attributes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payload_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPayload());
      }
      if (nonce_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, nonce_);
      }
      if (fee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fee_);
      }
      if (!attributes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, attributes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransactionP.UnsignedTx)) {
        return super.equals(obj);
      }
      TransactionP.UnsignedTx other = (TransactionP.UnsignedTx) obj;

      boolean result = true;
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && (getNonce()
          == other.getNonce());
      result = result && (getFee()
          == other.getFee());
      result = result && getAttributes()
          .equals(other.getAttributes());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNonce());
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFee());
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransactionP.UnsignedTx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionP.UnsignedTx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionP.UnsignedTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionP.UnsignedTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionP.UnsignedTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionP.UnsignedTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionP.UnsignedTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionP.UnsignedTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionP.UnsignedTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransactionP.UnsignedTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionP.UnsignedTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionP.UnsignedTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransactionP.UnsignedTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.UnsignedTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.UnsignedTx)
        TransactionP.UnsignedTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransactionP.internal_static_jsmith_nknsdk_network_proto_UnsignedTx_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransactionP.internal_static_jsmith_nknsdk_network_proto_UnsignedTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransactionP.UnsignedTx.class, TransactionP.UnsignedTx.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.Transaction.UnsignedTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (payloadBuilder_ == null) {
          payload_ = null;
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }
        nonce_ = 0L;

        fee_ = 0L;

        attributes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransactionP.internal_static_jsmith_nknsdk_network_proto_UnsignedTx_descriptor;
      }

      @java.lang.Override
      public TransactionP.UnsignedTx getDefaultInstanceForType() {
        return TransactionP.UnsignedTx.getDefaultInstance();
      }

      @java.lang.Override
      public TransactionP.UnsignedTx build() {
        TransactionP.UnsignedTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransactionP.UnsignedTx buildPartial() {
        TransactionP.UnsignedTx result = new TransactionP.UnsignedTx(this);
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        result.nonce_ = nonce_;
        result.fee_ = fee_;
        result.attributes_ = attributes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransactionP.UnsignedTx) {
          return mergeFrom((TransactionP.UnsignedTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransactionP.UnsignedTx other) {
        if (other == TransactionP.UnsignedTx.getDefaultInstance()) return this;
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        if (other.getNonce() != 0L) {
          setNonce(other.getNonce());
        }
        if (other.getFee() != 0L) {
          setFee(other.getFee());
        }
        if (other.getAttributes() != com.google.protobuf.ByteString.EMPTY) {
          setAttributes(other.getAttributes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransactionP.UnsignedTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransactionP.UnsignedTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private TransactionpayloadP.TransactionPayload payload_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionpayloadP.TransactionPayload, TransactionpayloadP.TransactionPayload.Builder, TransactionpayloadP.TransactionPayloadOrBuilder> payloadBuilder_;
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public boolean hasPayload() {
        return payloadBuilder_ != null || payload_ != null;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public TransactionpayloadP.TransactionPayload getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? TransactionpayloadP.TransactionPayload.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public Builder setPayload(TransactionpayloadP.TransactionPayload value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public Builder setPayload(
          TransactionpayloadP.TransactionPayload.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public Builder mergePayload(TransactionpayloadP.TransactionPayload value) {
        if (payloadBuilder_ == null) {
          if (payload_ != null) {
            payload_ =
              TransactionpayloadP.TransactionPayload.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = null;
          onChanged();
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public TransactionpayloadP.TransactionPayload.Builder getPayloadBuilder() {
        
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      public TransactionpayloadP.TransactionPayloadOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              TransactionpayloadP.TransactionPayload.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.TransactionPayload payload = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionpayloadP.TransactionPayload, TransactionpayloadP.TransactionPayload.Builder, TransactionpayloadP.TransactionPayloadOrBuilder>
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransactionpayloadP.TransactionPayload, TransactionpayloadP.TransactionPayload.Builder, TransactionpayloadP.TransactionPayloadOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }

      private long nonce_ ;
      /**
       * <code>uint64 nonce = 2;</code>
       */
      public long getNonce() {
        return nonce_;
      }
      /**
       * <code>uint64 nonce = 2;</code>
       */
      public Builder setNonce(long value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 nonce = 2;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private long fee_ ;
      /**
       * <code>int64 fee = 3;</code>
       */
      public long getFee() {
        return fee_;
      }
      /**
       * <code>int64 fee = 3;</code>
       */
      public Builder setFee(long value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fee = 3;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString attributes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes attributes = 4;</code>
       */
      public com.google.protobuf.ByteString getAttributes() {
        return attributes_;
      }
      /**
       * <code>bytes attributes = 4;</code>
       */
      public Builder setAttributes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        attributes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes attributes = 4;</code>
       */
      public Builder clearAttributes() {
        
        attributes_ = getDefaultInstance().getAttributes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.UnsignedTx)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.UnsignedTx)
    private static final TransactionP.UnsignedTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransactionP.UnsignedTx();
    }

    public static TransactionP.UnsignedTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnsignedTx>
        PARSER = new com.google.protobuf.AbstractParser<UnsignedTx>() {
      @java.lang.Override
      public UnsignedTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnsignedTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnsignedTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnsignedTx> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransactionP.UnsignedTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsmith.nknsdk.network.proto.MsgTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
     */
    boolean hasUnsignedTx();
    /**
     * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
     */
    TransactionP.UnsignedTx getUnsignedTx();
    /**
     * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
     */
    TransactionP.UnsignedTxOrBuilder getUnsignedTxOrBuilder();

    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    java.util.List<PorgramP.Program>
        getProgramsList();
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    PorgramP.Program getPrograms(int index);
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    int getProgramsCount();
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    java.util.List<? extends PorgramP.ProgramOrBuilder>
        getProgramsOrBuilderList();
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    PorgramP.ProgramOrBuilder getProgramsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code jsmith.nknsdk.network.proto.MsgTx}
   */
  public  static final class MsgTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jsmith.nknsdk.network.proto.MsgTx)
      MsgTxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgTx.newBuilder() to construct.
    private MsgTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgTx() {
      programs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              TransactionP.UnsignedTx.Builder subBuilder = null;
              if (unsignedTx_ != null) {
                subBuilder = unsignedTx_.toBuilder();
              }
              unsignedTx_ = input.readMessage(TransactionP.UnsignedTx.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(unsignedTx_);
                unsignedTx_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                programs_ = new java.util.ArrayList<PorgramP.Program>();
                mutable_bitField0_ |= 0x00000002;
              }
              programs_.add(
                  input.readMessage(PorgramP.Program.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          programs_ = java.util.Collections.unmodifiableList(programs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransactionP.internal_static_jsmith_nknsdk_network_proto_MsgTx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransactionP.internal_static_jsmith_nknsdk_network_proto_MsgTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransactionP.MsgTx.class, TransactionP.MsgTx.Builder.class);
    }

    private int bitField0_;
    public static final int UNSIGNED_TX_FIELD_NUMBER = 1;
    private TransactionP.UnsignedTx unsignedTx_;
    /**
     * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
     */
    public boolean hasUnsignedTx() {
      return unsignedTx_ != null;
    }
    /**
     * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
     */
    public TransactionP.UnsignedTx getUnsignedTx() {
      return unsignedTx_ == null ? TransactionP.UnsignedTx.getDefaultInstance() : unsignedTx_;
    }
    /**
     * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
     */
    public TransactionP.UnsignedTxOrBuilder getUnsignedTxOrBuilder() {
      return getUnsignedTx();
    }

    public static final int PROGRAMS_FIELD_NUMBER = 2;
    private java.util.List<PorgramP.Program> programs_;
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    public java.util.List<PorgramP.Program> getProgramsList() {
      return programs_;
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    public java.util.List<? extends PorgramP.ProgramOrBuilder>
        getProgramsOrBuilderList() {
      return programs_;
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    public int getProgramsCount() {
      return programs_.size();
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    public PorgramP.Program getPrograms(int index) {
      return programs_.get(index);
    }
    /**
     * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
     */
    public PorgramP.ProgramOrBuilder getProgramsOrBuilder(
        int index) {
      return programs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (unsignedTx_ != null) {
        output.writeMessage(1, getUnsignedTx());
      }
      for (int i = 0; i < programs_.size(); i++) {
        output.writeMessage(2, programs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (unsignedTx_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUnsignedTx());
      }
      for (int i = 0; i < programs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, programs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransactionP.MsgTx)) {
        return super.equals(obj);
      }
      TransactionP.MsgTx other = (TransactionP.MsgTx) obj;

      boolean result = true;
      result = result && (hasUnsignedTx() == other.hasUnsignedTx());
      if (hasUnsignedTx()) {
        result = result && getUnsignedTx()
            .equals(other.getUnsignedTx());
      }
      result = result && getProgramsList()
          .equals(other.getProgramsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnsignedTx()) {
        hash = (37 * hash) + UNSIGNED_TX_FIELD_NUMBER;
        hash = (53 * hash) + getUnsignedTx().hashCode();
      }
      if (getProgramsCount() > 0) {
        hash = (37 * hash) + PROGRAMS_FIELD_NUMBER;
        hash = (53 * hash) + getProgramsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransactionP.MsgTx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionP.MsgTx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionP.MsgTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionP.MsgTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionP.MsgTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionP.MsgTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionP.MsgTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionP.MsgTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionP.MsgTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransactionP.MsgTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionP.MsgTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionP.MsgTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransactionP.MsgTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jsmith.nknsdk.network.proto.MsgTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jsmith.nknsdk.network.proto.MsgTx)
        TransactionP.MsgTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransactionP.internal_static_jsmith_nknsdk_network_proto_MsgTx_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransactionP.internal_static_jsmith_nknsdk_network_proto_MsgTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransactionP.MsgTx.class, TransactionP.MsgTx.Builder.class);
      }

      // Construct using jsmith.nknsdk.network.proto.Transaction.MsgTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProgramsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (unsignedTxBuilder_ == null) {
          unsignedTx_ = null;
        } else {
          unsignedTx_ = null;
          unsignedTxBuilder_ = null;
        }
        if (programsBuilder_ == null) {
          programs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          programsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransactionP.internal_static_jsmith_nknsdk_network_proto_MsgTx_descriptor;
      }

      @java.lang.Override
      public TransactionP.MsgTx getDefaultInstanceForType() {
        return TransactionP.MsgTx.getDefaultInstance();
      }

      @java.lang.Override
      public TransactionP.MsgTx build() {
        TransactionP.MsgTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransactionP.MsgTx buildPartial() {
        TransactionP.MsgTx result = new TransactionP.MsgTx(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (unsignedTxBuilder_ == null) {
          result.unsignedTx_ = unsignedTx_;
        } else {
          result.unsignedTx_ = unsignedTxBuilder_.build();
        }
        if (programsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            programs_ = java.util.Collections.unmodifiableList(programs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.programs_ = programs_;
        } else {
          result.programs_ = programsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransactionP.MsgTx) {
          return mergeFrom((TransactionP.MsgTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransactionP.MsgTx other) {
        if (other == TransactionP.MsgTx.getDefaultInstance()) return this;
        if (other.hasUnsignedTx()) {
          mergeUnsignedTx(other.getUnsignedTx());
        }
        if (programsBuilder_ == null) {
          if (!other.programs_.isEmpty()) {
            if (programs_.isEmpty()) {
              programs_ = other.programs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureProgramsIsMutable();
              programs_.addAll(other.programs_);
            }
            onChanged();
          }
        } else {
          if (!other.programs_.isEmpty()) {
            if (programsBuilder_.isEmpty()) {
              programsBuilder_.dispose();
              programsBuilder_ = null;
              programs_ = other.programs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              programsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProgramsFieldBuilder() : null;
            } else {
              programsBuilder_.addAllMessages(other.programs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransactionP.MsgTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransactionP.MsgTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private TransactionP.UnsignedTx unsignedTx_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionP.UnsignedTx, TransactionP.UnsignedTx.Builder, TransactionP.UnsignedTxOrBuilder> unsignedTxBuilder_;
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public boolean hasUnsignedTx() {
        return unsignedTxBuilder_ != null || unsignedTx_ != null;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public TransactionP.UnsignedTx getUnsignedTx() {
        if (unsignedTxBuilder_ == null) {
          return unsignedTx_ == null ? TransactionP.UnsignedTx.getDefaultInstance() : unsignedTx_;
        } else {
          return unsignedTxBuilder_.getMessage();
        }
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public Builder setUnsignedTx(TransactionP.UnsignedTx value) {
        if (unsignedTxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          unsignedTx_ = value;
          onChanged();
        } else {
          unsignedTxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public Builder setUnsignedTx(
          TransactionP.UnsignedTx.Builder builderForValue) {
        if (unsignedTxBuilder_ == null) {
          unsignedTx_ = builderForValue.build();
          onChanged();
        } else {
          unsignedTxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public Builder mergeUnsignedTx(TransactionP.UnsignedTx value) {
        if (unsignedTxBuilder_ == null) {
          if (unsignedTx_ != null) {
            unsignedTx_ =
              TransactionP.UnsignedTx.newBuilder(unsignedTx_).mergeFrom(value).buildPartial();
          } else {
            unsignedTx_ = value;
          }
          onChanged();
        } else {
          unsignedTxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public Builder clearUnsignedTx() {
        if (unsignedTxBuilder_ == null) {
          unsignedTx_ = null;
          onChanged();
        } else {
          unsignedTx_ = null;
          unsignedTxBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public TransactionP.UnsignedTx.Builder getUnsignedTxBuilder() {
        
        onChanged();
        return getUnsignedTxFieldBuilder().getBuilder();
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      public TransactionP.UnsignedTxOrBuilder getUnsignedTxOrBuilder() {
        if (unsignedTxBuilder_ != null) {
          return unsignedTxBuilder_.getMessageOrBuilder();
        } else {
          return unsignedTx_ == null ?
              TransactionP.UnsignedTx.getDefaultInstance() : unsignedTx_;
        }
      }
      /**
       * <code>.jsmith.nknsdk.network.proto.UnsignedTx unsigned_tx = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionP.UnsignedTx, TransactionP.UnsignedTx.Builder, TransactionP.UnsignedTxOrBuilder>
          getUnsignedTxFieldBuilder() {
        if (unsignedTxBuilder_ == null) {
          unsignedTxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransactionP.UnsignedTx, TransactionP.UnsignedTx.Builder, TransactionP.UnsignedTxOrBuilder>(
                  getUnsignedTx(),
                  getParentForChildren(),
                  isClean());
          unsignedTx_ = null;
        }
        return unsignedTxBuilder_;
      }

      private java.util.List<PorgramP.Program> programs_ =
        java.util.Collections.emptyList();
      private void ensureProgramsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          programs_ = new java.util.ArrayList<PorgramP.Program>(programs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PorgramP.Program, PorgramP.Program.Builder, PorgramP.ProgramOrBuilder> programsBuilder_;

      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public java.util.List<PorgramP.Program> getProgramsList() {
        if (programsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(programs_);
        } else {
          return programsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public int getProgramsCount() {
        if (programsBuilder_ == null) {
          return programs_.size();
        } else {
          return programsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public PorgramP.Program getPrograms(int index) {
        if (programsBuilder_ == null) {
          return programs_.get(index);
        } else {
          return programsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder setPrograms(
          int index, PorgramP.Program value) {
        if (programsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProgramsIsMutable();
          programs_.set(index, value);
          onChanged();
        } else {
          programsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder setPrograms(
          int index, PorgramP.Program.Builder builderForValue) {
        if (programsBuilder_ == null) {
          ensureProgramsIsMutable();
          programs_.set(index, builderForValue.build());
          onChanged();
        } else {
          programsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder addPrograms(PorgramP.Program value) {
        if (programsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProgramsIsMutable();
          programs_.add(value);
          onChanged();
        } else {
          programsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder addPrograms(
          int index, PorgramP.Program value) {
        if (programsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProgramsIsMutable();
          programs_.add(index, value);
          onChanged();
        } else {
          programsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder addPrograms(
          PorgramP.Program.Builder builderForValue) {
        if (programsBuilder_ == null) {
          ensureProgramsIsMutable();
          programs_.add(builderForValue.build());
          onChanged();
        } else {
          programsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder addPrograms(
          int index, PorgramP.Program.Builder builderForValue) {
        if (programsBuilder_ == null) {
          ensureProgramsIsMutable();
          programs_.add(index, builderForValue.build());
          onChanged();
        } else {
          programsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder addAllPrograms(
          java.lang.Iterable<? extends PorgramP.Program> values) {
        if (programsBuilder_ == null) {
          ensureProgramsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, programs_);
          onChanged();
        } else {
          programsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder clearPrograms() {
        if (programsBuilder_ == null) {
          programs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          programsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public Builder removePrograms(int index) {
        if (programsBuilder_ == null) {
          ensureProgramsIsMutable();
          programs_.remove(index);
          onChanged();
        } else {
          programsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public PorgramP.Program.Builder getProgramsBuilder(
          int index) {
        return getProgramsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public PorgramP.ProgramOrBuilder getProgramsOrBuilder(
          int index) {
        if (programsBuilder_ == null) {
          return programs_.get(index);  } else {
          return programsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public java.util.List<? extends PorgramP.ProgramOrBuilder>
           getProgramsOrBuilderList() {
        if (programsBuilder_ != null) {
          return programsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(programs_);
        }
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public PorgramP.Program.Builder addProgramsBuilder() {
        return getProgramsFieldBuilder().addBuilder(
            PorgramP.Program.getDefaultInstance());
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public PorgramP.Program.Builder addProgramsBuilder(
          int index) {
        return getProgramsFieldBuilder().addBuilder(
            index, PorgramP.Program.getDefaultInstance());
      }
      /**
       * <code>repeated .jsmith.nknsdk.network.proto.Program programs = 2;</code>
       */
      public java.util.List<PorgramP.Program.Builder>
           getProgramsBuilderList() {
        return getProgramsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PorgramP.Program, PorgramP.Program.Builder, PorgramP.ProgramOrBuilder>
          getProgramsFieldBuilder() {
        if (programsBuilder_ == null) {
          programsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PorgramP.Program, PorgramP.Program.Builder, PorgramP.ProgramOrBuilder>(
                  programs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          programs_ = null;
        }
        return programsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jsmith.nknsdk.network.proto.MsgTx)
    }

    // @@protoc_insertion_point(class_scope:jsmith.nknsdk.network.proto.MsgTx)
    private static final TransactionP.MsgTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransactionP.MsgTx();
    }

    public static TransactionP.MsgTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgTx>
        PARSER = new com.google.protobuf.AbstractParser<MsgTx>() {
      @java.lang.Override
      public MsgTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgTx> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransactionP.MsgTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_UnsignedTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_UnsignedTx_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jsmith_nknsdk_network_proto_MsgTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jsmith_nknsdk_network_proto_MsgTx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-jsmith/nknsdk/network/proto/transactio" +
      "n.proto\022\033jsmith.nknsdk.network.proto\0324js" +
      "mith/nknsdk/network/proto/transactionpay" +
      "load.proto\032)jsmith/nknsdk/network/proto/" +
      "programP.proto\"~\n\nUnsignedTx\022@\n\007payload\030\001" +
      " \001(\0132/.jsmith.nknsdk.network.proto.Trans" +
      "actionPayload\022\r\n\005nonce\030\002 \001(\004\022\013\n\003fee\030\003 \001(" +
      "\003\022\022\n\nattributes\030\004 \001(\014\"}\n\005MsgTx\022<\n\013unsign" +
      "ed_tx\030\001 \001(\0132\'.jsmith.nknsdk.network.prot" +
      "o.UnsignedTx\0226\n\010programs\030\002 \003(\0132$.jsmith." +
      "nknsdk.network.proto.Programb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TransactionpayloadP.getDescriptor(),
          PorgramP.getDescriptor(),
        }, assigner);
    internal_static_jsmith_nknsdk_network_proto_UnsignedTx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jsmith_nknsdk_network_proto_UnsignedTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_UnsignedTx_descriptor,
        new java.lang.String[] { "Payload", "Nonce", "Fee", "Attributes", });
    internal_static_jsmith_nknsdk_network_proto_MsgTx_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jsmith_nknsdk_network_proto_MsgTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jsmith_nknsdk_network_proto_MsgTx_descriptor,
        new java.lang.String[] { "UnsignedTx", "Programs", });
    TransactionpayloadP.getDescriptor();
    PorgramP.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
